#!/usr/bin/env bash
#Displays the record type and the destination of a domain
output() {
	res=$(dig "$2.$1" | grep -A1 ';; ANSWER SECTION:')
	dest=$(echo "$res" | awk 'NR == 2 {print $NF}')
	rec=$(echo "$res" | awk 'NR == 2 {print $4}')
	echo "The subdomain $2 is a $rec record and points to $dest"
}

if [ -z "$2" ]; then
	output "$1" www
	output "$1" lb-01
	output "$1" web-01
	output "$1" web-02
else
	output "$1" "$2"
fi
