#!/usr/bin/env bash
# script that configures a new Ubuntu machine to respect above requirements (this script will be run on the server itself
sudo apt -y update
sudo apt -y install nginx
sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'
sudo service nginx start
