#!/usr/bin/env bash
# script that configures a new Ubuntu machine to respect above requirements (this script will be run on the server itself
sudo apt -y update
sudo apt -y install nginx
sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'
sudo service nginx start
sudo sed -i "47i\\	  location /redirect_me {\n                return 301 /;\n        }" /etc/nginx/sites-available/default
sudo service nginx reload
