#!/usr/bin/env bash
#Bash script that configures an Ubuntu server.
sed -i s/^127.*$// /etc/hosts
sudo tee -a /etc/hosts <<< "127.0.0.2 localhost" > /dev/null
sudo tee -a /etc/hosts <<< "8.8.8.8 facebook.com" > /dev/null
